# Generated by Django 4.2.20 on 2025-05-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0001_initial'),
        ('customer', '0001_initial'),
        ('chat', '0003_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_messages', to='serviceprovider.retailer'),
        ),
    ]
