# Generated by Django 4.2.20 on 2025-05-13 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0002_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='username',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
