# Generated by Django 4.2.20 on 2025-05-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('service_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website_link', models.URLField(max_length=500)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='serviceprovider.retailer')),
            ],
        ),
    ]
