# Generated by Django 4.2.20 on 2025-05-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceprovider', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='username',
        ),
        migrations.AddField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_entries', models.IntegerField(default=1)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.retailer')),
            ],
        ),
    ]
