# Generated by Django 4.2.20 on 2025-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0003_remove_retailer_email_remove_retailer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
