# Generated by Django 4.2.20 on 2025-05-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_remove_customer_email_remove_customer_password_and_more'),
        ('serviceprovider', '0004_job_location'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='retailer',
        #     name='business_name',
        #     field=models.CharField(default='N/A', max_length=255),
        # ),
        migrations.AlterField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.retailer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
