# Generated by Django 4.2.20 on 2025-05-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceprovider', '0005_retailer_business_name_alter_retailer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='business_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL),
        ),
    ]
