# Generated by Django 4.2.20 on 2025-05-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0006_retailer_business_name_alter_retailer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='business_name',
        ),
    ]
