# Generated by Django 4.2.20 on 2025-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0007_remove_retailer_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
